version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    container_name: nmi_db
    environment:
      POSTGRES_USER: nmi_user
      POSTGRES_PASSWORD: nmi_pass
      POSTGRES_DB: nmi_produksie
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: nmi_backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://nmi_user:nmi_pass@db:5432/nmi_produksie
    volumes:
      - ./backend:/app
    command: npm run dev

volumes:
  pgdata:
